### PR TITLE
Fix put session endpoint

### LINKED ISSUE #130: Fix implementation of put Session
As described in the PR #129 : 
* [ ] Set timestamps correctly
* [ ] Handle case where the session is already in the database

### PR DESCRIPTION
**Pull request by glsubri**
I would have loved to add some unit testing, but unfortunately, I don't really see how I can do a mockup of this. Any help would be appreciated.

I've done some manual tests though and it seems to work.

This should fix #130

### CODE REVIEW

**Review by GTZL1 — APPROVED** [review]

File: src/main/java/ch/heigvd/pro/b04/sessions/SessionController.java [hunk 1]
```diff
@@ -128,18 +133,59 @@ public ServerSession putSession(
...
+            session.close();
+            break;
+          default:
+            throw new IllegalSessionStateException();
+        }
+      } else if (session.getState().equals(SessionState.QUARANTINED)) {
+        switch (askedState) {
+          case OPEN:
+          case QUARANTINED:
+            throw new SessionStateMustBeClosedFirstException();
```
Comment (alexandrepiveteau) [inline src/main/java/ch/heigvd/pro/b04/sessions/SessionController.java:168]: We probably have to discuss whether this is the behavior we expect in class. Don't we want to offer flexibility to the user and let them open the poll "again" with the same access code ?

**Review by alexandrepiveteau — APPROVED** [review]
